import { readFileSync } from 'node:fs';
import { getContract } from './contract.js';
import { CoreError } from './errors.js';

export type DocsTopic = 'concepts' | 'format' | 'fields' | 'api';
const docFiles: Record<Exclude<DocsTopic, 'fields'>, string> = {
  concepts: 'concepts.md', format: 'format.md', api: 'README.md',
};
type SchemaNode = {
  properties?: Record<string, SchemaNode>; required?: string[]; default?: unknown;
  type?: string; const?: unknown; enum?: unknown[];
};

/** Field reference is rendered from the same snapshot exposed to consumers. */
export function getDocs(topic: DocsTopic): string {
  if (topic === 'fields') {
    const contract = getContract();
    const sections = Object.entries(contract.kinds).map(([kind, value]) => {
      const rows = Object.entries(value.fields).map(([name, meaning]) => {
        const schema = value.schema as SchemaNode;
        const [parent, child] = name.split('.');
        const container = child ? schema.properties![parent!]! : schema;
        const property = container.properties![child ?? parent!]!;
        const required = container.required?.includes(child ?? parent!) ? 'có' : 'không';
        const fallback = 'default' in property ? JSON.stringify(property.default) : '—';
        const type = property.const !== undefined ? JSON.stringify(property.const)
          : property.enum ? property.enum.join(' / ') : property.type;
        return `| ${name} | ${type} | ${required} | ${fallback} | ${meaning.category} | ${meaning.description} |`;
      });
      return `## ${kind}\n\n| Field | Kiểu/giá trị | Bắt buộc ở input | Mặc định | Nhóm | Ý nghĩa |\n|---|---|---|---|---|---|\n${rows.join('\n')}`;
    });
    return `<!-- Generated by npm run core:docs. Do not edit by hand. -->\n\n# Field reference — contract ${contract.contractVersion}\n\n${sections.join('\n\n')}\n\n## Ràng buộc\n\n${contract.rules.map(rule => `- ${rule}`).join('\n')}\n`;
  }
  if (!Object.hasOwn(docFiles, topic)) {
    throw new CoreError('UNKNOWN_DOCS_TOPIC', `Unknown core docs topic: ${String(topic)}`);
  }
  try { return readFileSync(new URL(`../docs/${docFiles[topic]}`, import.meta.url), 'utf8'); }
  catch (cause) {
    throw new CoreError('DOCS_UNAVAILABLE', `Cannot read core docs topic: ${topic}`, { cause });
  }
}
